### ISSUE TITLE
양조장 DB 관리

### ISSUE THREAD

**Issue by taeuk-gang** [mac-tour/mac-tour#14]
## 목표
메인 페이지 - 양조장 DB 관리
## 진행 사항

- [x] 메인 페이지 양조장 DB 입력

## 다음 목표

- 미정

**Comment by Juyudang** [comment]
# DB 넣은 기준

1. 양조장 투어를 지원하는가
   - no : 데이터 넣지 않음
   - yes : 밑으로
2. 신청하는 독자적인 사이트가 있는가
   - yes : <b>데이터 넣음</b>
   - no : 밑으로
3. 홈페이지에 양조장 투어가 명시되어 있는가
   - yes : <b>Contact Us 등 연락 방법 명시 및 데이터 넣음</b>
   - no : 밑으로
4. 직접 물어봄
   - yes : <b>해당 방법 명시 및 데이터 넣음</b>
   - no : 나중에 추가
