### ISSUE TITLE
회의록

### ISSUE THREAD

**Issue by minhyeoky** [mac-tour/mac-tour#2]
# 일정

## 1주차(9/1 ~ 9/7)
1. Github organization, repo 생성
2. Slack 생성
   1. Git bot App 연동
3. 개발환경 셋팅
   1. PhoneGap을 활용한 모바일 Hello world 띄우기
   2. GCP App Engine 에 Flask & swagger 배포 해보기
4. 승민, 태욱: phone gap 학습 후 문서화
5. 민혁: API 데이터 확인 -> 데이터베이스 스키마 작성 후 문서화
6. 태욱: 구글 스토어 개발자 신청
------
### 이슈
1. 양조장의 개수가 너무 작다. (약 10여개)
   1. 회사는 많지만, 양조장 투어까지 설비가 되어 있는 곳은 적다.

### 메인페이지 레이아웃 변동사항

1. 카드형태의 배너를 상단에 삽입 -> (소식, 공지사항, 이벤트)등을 알리기
2. 양조장 소개할 이미지 (웹에서 얻은 이미지 등을 사용해도 되는가?)
   1. 스트리트뷰는 지저분할 것 같기 때문에 X
3. 왼쪽 위에 로고와 양조장 이름
4. 오른쪽 아래에 넣을 (#태그)
   - 지역… (추가하기)
5. 태그 정렬기능
6. 검색기능은 X
7. 하단부 버튼도 없애기
8. 상단: |뒤로가기|로고(클릭시 홈바로가기)|지역선택

### 상세페이지 레이아웃 변동사항

![image-20190831235914611](https://tva1.sinaimg.cn/large/006y8mN6gy1g6j97vbe9tj30650but91.jpg)

1. 상단바, 양조장 사진은 유지
2. 양조장 사진 밑에는 홈페이지, 길찾기, 공유 버튼(카카오톡, SNS)
3. 양조장 소개 글
4. **Tmap 지도 - 양조장을 중심으로 맛집, 관광지 pin**
5. 하단바: 가격, 일정 안내 | 신청하기 버튼
   1. 신청하기
   2. 해당 신청 사이트로 redirect(가능하다면, 어플상에서)
6. 지도상의 핀을 누르면 밑에 있는 주변 관광지 카드로 바로 이동
   1. 스크롤이 길어질 수 있기 때문에, Top 가는 버튼 고정

------

**Comment by taeuk-gang** [comment]
다했다요
