### ISSUE TITLE
상세 페이지 구현

### ISSUE THREAD

**Issue by Juyudang** [mac-tour/mac-tour#8]
## 목표
상단 양조장 사진 슬라이드 구현
양조장 설명 추가
홈페이지, 길찾기, 공유 버튼 추가
티맵 추가
근처 관광지 등 정보 추가

## 진행 사항

- [x] 양조장 슬라이드 구현
- [x] 양조장 설명 추가
- [x] 버튼 3종 추가
- [ ] 공유 버튼 활성화

## 다음 목표
- [x] 티맵 기능 점진적 추가
- [x] 근처 관광지 연동

**Comment by taeuk-gang** [comment]
바톤 터치!, 이제 내가 마무리할게
![터치2](https://user-images.githubusercontent.com/26294469/65362421-424ff780-dc42-11e9-8e86-9eafa1fe1b4f.gif)

**Comment by Juyudang** [comment]
![You I](https://user-images.githubusercontent.com/40845064/65362454-64e21080-dc42-11e9-9347-94351d590b41.gif)
『 #14 착수한다 』
